# $(ICPCONFIGDIR) or $(ICPCONFIGROOT) ?
$(IFIOC_GALIL_01) epicsEnvSet "LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/pinhole_selector.txt"
$(IFIOC_GALIL_04) epicsEnvSet "LOOKUPFILE2" "$(ICPCONFIGROOT)/motionSetPoints/monitor9.txt"

$(IFIOC_GALIL_01) motionSetPointsConfigure("LOOKUPFILE1","LOOKUPFILE1", 1)
$(IFIOC_GALIL_04) motionSetPointsConfigure("LOOKUPFILE2","LOOKUPFILE2", 1)

$(IFIOC_GALIL_01) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:PINHOLE:,AXIS0=$(MYPVPREFIX)MOT:PINHOLE,TOL=1,LOOKUP=LOOKUPFILE1")
$(IFIOC_GALIL_04) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:MON9:,AXIS0=$(MYPVPREFIX)MOT:M9,TOL=1,LOOKUP=LOOKUPFILE2")
$(IFIOC_GALIL_01) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:PINHOLE:,AXIS0=$(MYPVPREFIX)MOT:PINHOLE,TOL=1,LOOKUP=LOOKUPFILE1","NUMPOS", 0, 30)
$(IFIOC_GALIL_04) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:MON9:,AXIS0=$(MYPVPREFIX)MOT:M9,TOL=1,LOOKUP=LOOKUPFILE2","NUMPOS", 0, 30)
