$(IFMTRCTRL2) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=SAMPLE:LIN,mAXIS=MTR0201")
$(IFMTRCTRL3) $(IFAXIS1) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=LET_V_SAMP_3POS,mAXIS=MTR0301")
