$(IFMTRCTRL2) epicsEnvSet "LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/low_temp_sample_changer.txt"

$(IFMTRCTRL2) motionSetPointsConfigure("LOOKUPFILE1","LOOKUPFILE1", 1)

$(IFMTRCTRL2) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,NAME0=linear,AXIS0=$(MYPVPREFIX)MOT:SAMPLE:LIN,LOOKUP=LOOKUPFILE1,TOL=0.1")

$(IFMTRCTRL2) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,NAME0=linear,AXIS0=$(MYPVPREFIX)MOT:SAMPLE:LIN,LOOKUP=LOOKUPFILE1", "NUMPOS", 0, 3)


$(IFMTRCTRL3) $(IFAXIS1) epicsEnvSet "LOOKUPFILE" "$(ICPCONFIGROOT)/motionSetPoints/LET_V_SAMP_3POS.txt"
$(IFMTRCTRL3) $(IFAXIS1) motionSetPointsConfigure("LOOKUPFILE","LOOKUPFILE", 1)
$(IFMTRCTRL3) $(IFAXIS1) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:LET_V_SAMP_3POS:,AXIS0=$(MYPVPREFIX)MOT:LET_V_SAMP_3POS,TOL=1,LOOKUP=LOOKUPFILE")
$(IFMTRCTRL3) $(IFAXIS1) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:LET_V_SAMP_3POS:,AXIS0=$(MYPVPREFIX)MOT:LET_V_SAMP_3POS,TOL=1,LOOKUP=LOOKUPFILE","NUMPOS", 0, 30)

