 # Setting up the Alignment Mirror
$(IFIOC_LINMOT_03) epicsEnvSet("LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/mirror.txt")

$(IFIOC_LINMOT_03) motionSetPointsConfigure("LOOKUPFILE1","LOOKUPFILE1", 1)

$(IFIOC_LINMOT_03) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:MIRROR:,NAME0=linear,AXIS0=$(MYPVPREFIX)MOT:MIRROR,TOL=0.1,LOOKUP=LOOKUPFILE1")

$(IFIOC_LINMOT_03) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:MIRROR:,AXIS0=$(MYPVPREFIX)MOT:MIRROR,TOL=1,LOOKUP=LOOKUPFILE1", "NUMPOS", 0, 2)
	