epicsEnvSet "LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/camera.txt"
epicsEnvSet "LOOKUPFILE2" "$(ICPCONFIGROOT)/motionSetPoints/sample_changer.txt"
motionSetPointsConfigure("LOOKUPFILE1","LOOKUPFILE1", 1)
motionSetPointsConfigure("LOOKUPFILE2","LOOKUPFILE2", 1)

dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:CAM:,NAME0=in,AXIS0=$(MYPVPREFIX)MOT:CAMERA,TOL=0.1,LOOKUP=LOOKUPFILE1")
dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:CAM:,NAME0=in,AXIS0=$(MYPVPREFIX)MOT:CAMERA,TOL=0.1,LOOKUP=LOOKUPFILE1","NUMPOS", 0, 30)

dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,NAME0=rotational,AXIS0=$(MYPVPREFIX)MOT:CHANGER,TOL=0.1,LOOKUP=LOOKUPFILE2")
dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,NAME0=rotational,AXIS0=$(MYPVPREFIX)MOT:CHANGER,TOL=0.1,LOOKUP=LOOKUPFILE2","NUMPOS", 0, 30)
