$(IFIOC_GALIL_01) epicsEnvSet "LOOKUP_JAWSINOUT_FILE" "$(ICPCONFIGROOT)/motionSetPoints/jawsinout.txt"
$(IFIOC_GALIL_01) motionSetPointsConfigure("LOOKUP_JAWSINOUT","LOOKUP_JAWSINOUT_FILE", 1)
$(IFIOC_GALIL_01) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)MOT:JAWSINOUT:,NAME0=Position,AXIS0=$(MYPVPREFIX)MOT:MTR0102,TOL=1,LOOKUP=LOOKUP_JAWSINOUT")
$(IFIOC_GALIL_01) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)MOT:JAWSINOUT:,NAME0=Position,AXIS0=$(MYPVPREFIX)MOT:MTR0102,TOL=1,LOOKUP=LOOKUP_JAWSINOUT","NUMPOS", 0, 2)
