epicsEnvSet "LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/pinhole_selector.txt"
epicsEnvSet "LOOKUPFILE2" "$(ICPCONFIGROOT)/motionSetPoints/monitor9.txt"

motionSetPointsConfigure("LOOKUPFILE1","LOOKUPFILE1", 1)
motionSetPointsConfigure("LOOKUPFILE2","LOOKUPFILE2", 1)

dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:PINHOLE:,AXIS0=$(MYPVPREFIX)MOT:PINHOLE,TOL=1,LOOKUP=LOOKUPFILE1")
dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:MON9:,AXIS0=$(MYPVPREFIX)MOT:M9,TOL=1,LOOKUP=LOOKUPFILE2")

dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:PINHOLE:,AXIS0=$(MYPVPREFIX)MOT:PINHOLE,TOL=1,LOOKUP=LOOKUPFILE1","NUMPOS", 0, 30)
dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:MON9:,AXIS0=$(MYPVPREFIX)MOT:M9,TOL=1,LOOKUP=LOOKUPFILE2","NUMPOS", 0, 30)
