$(IFIOC_GALIL_04) epicsEnvSet "LOOKUP_SC_FILE" "$(ICPCONFIGROOT)/motionSetPoints/sample.txt"
$(IFIOC_GALIL_04) epicsEnvSet "LOOKUP_CAM_FILE" "$(ICPCONFIGROOT)/motionSetPoints/camera.txt"
$(IFIOC_GALIL_04) motionSetPointsConfigure("LOOKUP_SC","LOOKUP_SC_FILE", 2)
$(IFIOC_GALIL_04) motionSetPointsConfigure("LOOKUP_CAM","LOOKUP_CAM_FILE", 1)
$(IFIOC_GALIL_04) 
$(IFIOC_GALIL_04) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsDoubleAxis.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,NAME0=Vertical,AXIS0=$(MYPVPREFIX)MOT:SAMPLE:VERT,NAME1=Rotation,AXIS1=$(MYPVPREFIX)MOT:SAMPLE:ROT,TOL=1,LOOKUP=LOOKUP_SC")
$(IFIOC_GALIL_04) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,NAME0=Vertical,AXIS0=$(MYPVPREFIX)MOT:SAMPLE:VERT,NAME1=Rotation,AXIS1=$(MYPVPREFIX)MOT:SAMPLE:ROT,TOL=1,LOOKUP=LOOKUP_SC","NUMPOS", 0, 30)
$(IFIOC_GALIL_04)
$(IFIOC_GALIL_04) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)CAMERA:,NAME0=Position,AXIS0=$(MYPVPREFIX)MOT:CAM,TOL=1,LOOKUP=LOOKUP_CAM")
$(IFIOC_GALIL_04) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)CAMERA:,NAME0=Position,AXIS0=$(MYPVPREFIX)MOT:CAM,NAME1=Rotation,TOL=1,LOOKUP=LOOKUP_CAM","NUMPOS", 0, 2)
