$(IFMTRCTRL1) $(IFAXIS1) epicsEnvSet "LOOKUPFILE" "$(ICPCONFIGROOT)/motionSetPoints/linsample.txt"
$(IFMTRCTRL1) $(IFAXIS1) motionSetPointsConfigure("LOOKUPFILE","LOOKUPFILE", 1)
$(IFMTRCTRL1) $(IFAXIS1) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:LSAMPLE:,AXIS0=$(MYPVPREFIX)MOT:STACK:LIN,TOL=1,LOOKUP=LOOKUPFILE")
$(IFMTRCTRL1) $(IFAXIS1) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:LSAMPLE:,AXIS0=$(MYPVPREFIX)MOT:STACK:LIN,TOL=1,LOOKUP=LOOKUPFILE","NUMPOS", 0, 30)

$(IFMTRCTRL3) $(IFAXIS1) epicsEnvSet "LOOKUPFILE" "$(ICPCONFIGROOT)/motionSetPoints/LET_V_SAMP_3POS.txt"
$(IFMTRCTRL3) $(IFAXIS1) motionSetPointsConfigure("LOOKUPFILE","LOOKUPFILE", 1)
$(IFMTRCTRL3) $(IFAXIS1) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:LET_V_SAMP_3POS:,AXIS0=$(MYPVPREFIX)MOT:LET_V_SAMP_3POS,TOL=1,LOOKUP=LOOKUPFILE")
$(IFMTRCTRL3) $(IFAXIS1) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:LET_V_SAMP_3POS:,AXIS0=$(MYPVPREFIX)MOT:LET_V_SAMP_3POS,TOL=1,LOOKUP=LOOKUPFILE","NUMPOS", 0, 30)
