
# Setting up the Sample Changer values
$(IFIOC_TC_01) epicsEnvSet "LOOKUPFILE2" "$(ICPCONFIGROOT)/motionSetPoints/sample.txt"
$(IFIOC_TC_01) motionSetPointsConfigure("LOOKUPFILE2","LOOKUPFILE2", 2)

$(IFIOC_TC_01) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,AXIS0=$(MYPVPREFIX)MOT:SAMPLE:LIN,AXIS1=$(MYPVPREFIX)MOT:SAMPLE:ROT,TOL=1,LOOKUP=LOOKUPFILE2","NUMPOS", 0, 15)
$(IFIOC_TC_01) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsDoubleAxis.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,AXIS0=$(MYPVPREFIX)MOT:SAMPLE:LIN,AXIS1=$(MYPVPREFIX)MOT:SAMPLE:ROT,TOL=1,LOOKUP=LOOKUPFILE2")

