
# Setting up the Sample Changer values
$(IFIOC_GALIL_03) epicsEnvSet "LOOKUPFILE2" "$(ICPCONFIGROOT)/motionSetPoints/sample.txt"
$(IFIOC_GALIL_03) motionSetPointsConfigure("LOOKUPFILE2","LOOKUPFILE2", 2)
$(IFIOC_GALIL_03) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsDoubleAxis.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,AXIS0=$(MYPVPREFIX)MOT:SAMP:X,AXIS1=$(MYPVPREFIX)MOT:SAMP:Y,TOL=1,LOOKUP=LOOKUPFILE2")

$(IFIOC_GALIL_03) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,AXIS0=$(MYPVPREFIX)MOT:SAMP:X,AXIS1=$(MYPVPREFIX)MOT:SAMP:Y,TOL=1,LOOKUP=LOOKUPFILE2","NUMPOS", 0, 30)