$(IFIOC_MCLEN_02=#) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FURNACE:HEIGHT,mAXIS=MTR0501")
$(IFIOC_MCLEN_02=#) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FURNACE:ROT,mAXIS=MTR0502")

