# Setting up the Be Filter values
$(IFIOC_GALIL_01) epicsEnvSet "LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/BeFilter.txt"
$(IFIOC_GALIL_01) motionSetPointsConfigure("LOOKUPFILE1","LOOKUPFILE1", 1)

$(IFIOC_GALIL_01) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:BEFILTER:,AXIS0=$(MYPVPREFIX)MOT:BEFILTER,TOL=1,LOOKUP=LOOKUPFILE1")
$(IFIOC_GALIL_01) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:BEFILTER:,AXIS0=$(MYPVPREFIX)MOT:BEFILTER,TOL=1,LOOKUP=LOOKUPFILE1","NUMPOS", 0, 30)
