$(IFIOC_GALIL_04) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=REARBAFFLEZ,mAXIS=MTR0408")
$(IFIOC_GALIL_05) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FRONTBAFFLEZ,mAXIS=MTR0503")

$(IFIOC_GALIL_05) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FRONTDETZ,mAXIS=MTR0501")
$(IFIOC_GALIL_05) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FRONTDETX,mAXIS=MTR0505")
$(IFIOC_GALIL_05) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FRONTDETROT,mAXIS=MTR0506")
$(IFIOC_GALIL_04) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=REARDETX,mAXIS=MTR0405")
$(IFIOC_GALIL_04) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=REARDETZ,mAXIS=MTR0401")

$(IFIOC_GALIL_04) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=BEAMSTOPX,mAXIS=MTR0402")
$(IFIOC_GALIL_04) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=BEAMSTOP2Y,mAXIS=MTR0403")
$(IFIOC_GALIL_04) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=BEAMSTOP1Y,mAXIS=MTR0406")
$(IFIOC_GALIL_04) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=BEAMSTOP3Y,mAXIS=MTR0407")
$(IFIOC_GALIL_05) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FRONTBEAMSTOP,mAXIS=MTR0502")

$(IFIOC_GALIL_04) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=REARSTRIP,mAXIS=MTR0404")
$(IFIOC_GALIL_05) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FRONTSTRIP,mAXIS=MTR0504")

$(IFIOC_GALIL_03) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=JAWRIGHT,mAXIS=MTR0301")
$(IFIOC_GALIL_03) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=JAWLEFT,mAXIS=MTR0302")
$(IFIOC_GALIL_03) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=JAWUP,mAXIS=MTR0303")
$(IFIOC_GALIL_03) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=JAWDOWN,mAXIS=MTR0304")

$(IFIOC_GALIL_05) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=SCRAPER,mAXIS=MTR0507")

$(IFIOC_GALIL_01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=APERTURE_1,mAXIS=MTR0101")
$(IFIOC_GALIL_01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=APERTURE_2,mAXIS=MTR0102")
$(IFIOC_GALIL_01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=APERTURE_3,mAXIS=MTR0103")
$(IFIOC_GALIL_01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=APERTURE_4,mAXIS=MTR0104")
$(IFIOC_GALIL_01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=APERTURE_5,mAXIS=MTR0105")

$(IFIOC_GALIL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=GUIDE_1,mAXIS=MTR0201")
$(IFIOC_GALIL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=GUIDE_2,mAXIS=MTR0202")
$(IFIOC_GALIL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=GUIDE_3,mAXIS=MTR0203")
$(IFIOC_GALIL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=GUIDE_4,mAXIS=MTR0204")
$(IFIOC_GALIL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=GUIDE_5,mAXIS=MTR0205")
