
caput IN:MOTION:MOT:MTR0501.DESC "SLIT TBC"
caput IN:MOTION:MOT:MTR0502.DESC "SLIT TBC"
caput IN:MOTION:MOT:MTR0503.DESC "SLIT TBC"
caput IN:MOTION:MOT:MTR0504.DESC "SLIT TBC"
						
						
caput IN:MOTION:MOT:MTR0505.DESC "ROTATION"
caput IN:MOTION:MOT:MTR0506.DESC "HORIZONTAL"
caput IN:MOTION:MOT:MTR0507.DESC "VERTICAL_1"
caput IN:MOTION:MOT:MTR0508.DESC "VERTICAL_2"
caput IN:MOTION:MOT:MTR0509.DESC "COMBINED_VERT"
						
						
caput IN:MOTION:MOT:MTR0510.DESC "DRAD_EXTERNAL"
caput IN:MOTION:MOT:MTR0511.DESC "DRAD_INTERNAL"
						
caput IN:MOTION:MOT:MTR0512.DESC "DOFF_EXTERNAL"
caput IN:MOTION:MOT:MTR0513.DESC "DOFF_INTERNAL"
						
caput IN:MOTION:MOT:MTR0514.DESC "INT_OFFS_ANGLE"
						
caput IN:MOTION:MOT:MTR0515.DESC "TANK_LENGTH"
caput IN:MOTION:MOT:MTR0516.DESC "PIVOT_TO_WINDOW"
						
caput IN:MOTION:MOT:MTR0517.DESC "DELTA"
caput IN:MOTION:MOT:MTR0518.DESC "TAU"
						
caput IN:MOTION:MOT:MTR0519.DESC "DRAD"
caput IN:MOTION:MOT:MTR0520.DESC "MEAS_ANGLE"
						
caput IN:MOTION:MOT:MTR0521.DESC "MEAS_ANGLE_OFF"
						
						
caput IN:MOTION:MOT:MTR0522.DESC "ROT_CALIB"
caput IN:MOTION:MOT:MTR0523.DESC "ROT_VIRTUAL"
caput IN:MOTION:MOT:MTR0524.DESC "ROT_SAMPLE"
						
caput IN:MOTION:MOT:MTR0525.DESC "VERT_CALIB"
caput IN:MOTION:MOT:MTR0526.DESC "VERT_SAMPLE"
caput IN:MOTION:MOT:MTR0527.DESC "VERT_VIRTUAL"
						
						
caput IN:MOTION:MOT:MTR0528.DESC "HORIZ_CALIB"
caput IN:MOTION:MOT:MTR0529.DESC "HORIZ_SAMPLE"
caput IN:MOTION:MOT:MTR0530.DESC "HORIZ_VIRTUAL"
