$(IFIOC_GALILMUL_01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=APERTURE_1,mAXIS=MTR0101")
$(IFIOC_GALILMUL_01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=APERTURE_2,mAXIS=MTR0102")
$(IFIOC_GALILMUL_01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=APERTURE_3,mAXIS=MTR0103")
$(IFIOC_GALILMUL_01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=APERTURE_4,mAXIS=MTR0104")
$(IFIOC_GALILMUL_01) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=APERTURE_5,mAXIS=MTR0105")



$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=REARBAFFLEZ,mAXIS=MTR0408")
$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FRONTBAFFLEZ,mAXIS=MTR0503")

$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FRONTDETZ,mAXIS=MTR0501")
$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FRONTDETX,mAXIS=MTR0505")
$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FRONTDETROT,mAXIS=MTR0506")
$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=REARDETX,mAXIS=MTR0405")
$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=REARDETZ,mAXIS=MTR0401")

$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=BEAMSTOPX,mAXIS=MTR0402")
$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=BEAMSTOP2Y,mAXIS=MTR0403")
$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=BEAMSTOP1Y,mAXIS=MTR0406")
$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=BEAMSTOP3Y,mAXIS=MTR0407")
$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FRONTBEAMSTOP,mAXIS=MTR0502")

$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=REARSTRIP,mAXIS=MTR0404")
$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=FRONTSTRIP,mAXIS=MTR0504")

$(IFIOC_GALILMUL_02) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=SCRAPER,mAXIS=MTR0507")
