$(IFIOC_GALILMUL_01) epicsEnvSet "LOOKUPFILE" "$(ICPCONFIGROOT)/motionSetPoints/aperture_and_guides.txt"

$(IFIOC_GALILMUL_01) motionSetPointsConfigure("LOOKUPFILE","LOOKUPFILE", 10)

$(IFIOC_GALILMUL_01) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints10Axis.db","P=$(MYPVPREFIX)LKUP:AG:,AXIS0=$(MYPVPREFIX)MOT:GUIDE_1,AXIS1=$(MYPVPREFIX)MOT:GUIDE_2,AXIS2=$(MYPVPREFIX)MOT:GUIDE_3,AXIS3=$(MYPVPREFIX)MOT:GUIDE_4,AXIS4=$(MYPVPREFIX)MOT:GUIDE_5,AXIS5=$(MYPVPREFIX)MOT:APERTURE_1,AXIS6=$(MYPVPREFIX)MOT:APERTURE_2,AXIS7=$(MYPVPREFIX)MOT:APERTURE_3,AXIS8=$(MYPVPREFIX)MOT:APERTURE_4,AXIS9=$(MYPVPREFIX)MOT:APERTURE_5,TOL=1,LOOKUP=LOOKUPFILE")

$(IFIOC_GALILMUL_02) epicsEnvSet "LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/scraper_aperture.txt"

$(IFIOC_GALILMUL_02) motionSetPointsConfigure("LOOKUPFILE1","LOOKUPFILE1", 1)

# The tolerance must be large to make sure that LOCN always points to the closest setpoint
$(IFIOC_GALILMUL_02) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:SCRAPER:,NAME1=SCRAPER,AXIS0=$(MYPVPREFIX)MOT:SCRAPER,TOL=1,LOOKUP=LOOKUPFILE1")

