$(IFIOC_MCLEN_01) epicsEnvSet "LOOKUP_SC_FILE" "$(ICPCONFIGROOT)/motionSetPoints/sample.txt"
$(IFIOC_MCLEN_01) motionSetPointsConfigure("LOOKUP_SC","LOOKUP_SC_FILE", 1)
$(IFIOC_MCLEN_01) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,NAME0=Position,AXIS0=$(MYPVPREFIX)MOT:MTR0301,TOL=1,LOOKUP=LOOKUP_SC")
$(IFIOC_MCLEN_01) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,NAME0=Position,AXIS0=$(MYPVPREFIX)MOT:MTR0301,TOL=1,LOOKUP=LOOKUP_SC","NUMPOS", 0, 4)
