# Setting up the PGC values
$(IFIOC_GALIL_01) epicsEnvSet "LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/PGC.txt"
$(IFIOC_GALIL_01) motionSetPointsConfigure("LOOKUPFILE1","LOOKUPFILE1", 1)

$(IFIOC_GALIL_01) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:PGC:,AXIS0=$(MYPVPREFIX)MOT:PGC,TOL=1,LOOKUP=LOOKUPFILE1")

# Setting up the Sample Changer values
$(IFIOC_GALIL_04) epicsEnvSet "LOOKUPFILE2" "$(ICPCONFIGROOT)/motionSetPoints/sample.txt"
$(IFIOC_GALIL_04) motionSetPointsConfigure("LOOKUPFILE2","LOOKUPFILE2", 2)
$(IFIOC_GALIL_04) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsDoubleAxis.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,AXIS0=$(MYPVPREFIX)MOT:STACK:Y,AXIS1=$(MYPVPREFIX)MOT:STACK:ZLO,TOL=1,LOOKUP=LOOKUPFILE2")

# Setting up the Monitor and laser alignment
$(IFIOC_GALIL_01) epicsEnvSet "LOOKUPFILE3" "$(ICPCONFIGROOT)/motionSetPoints/laser.txt"
$(IFIOC_GALIL_01) motionSetPointsConfigure("LOOKUPFILE3","LOOKUPFILE3", 1)
$(IFIOC_GALIL_01) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:LSR:,AXIS0=$(MYPVPREFIX)MOT:LASER,TOL=1,LOOKUP=LOOKUPFILE3")

$(IFIOC_GALIL_01) epicsEnvSet "LOOKUPFILE4" "$(ICPCONFIGROOT)/motionSetPoints/monitor3.txt"
$(IFIOC_GALIL_01) motionSetPointsConfigure("LOOKUPFILE4","LOOKUPFILE4", 1)
$(IFIOC_GALIL_01) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:MON3:,AXIS0=$(MYPVPREFIX)MOT:MON3,TOL=1,LOOKUP=LOOKUPFILE4")

$(IFIOC_GALIL_01) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:PGC:,AXIS0=$(MYPVPREFIX)MOT:PGC,TOL=1,LOOKUP=LOOKUPFILE1","NUMPOS", 0, 30)
$(IFIOC_GALIL_04) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,AXIS0=$(MYPVPREFIX)MOT:STACK:Y,AXIS1=$(MYPVPREFIX)MOT:STACK:ZLO,TOL=1,LOOKUP=LOOKUPFILE2","NUMPOS", 0, 30)
$(IFIOC_GALIL_01) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:LSR:,AXIS0=$(MYPVPREFIX)MOT:LASER,TOL=1,LOOKUP=LOOKUPFILE3","NUMPOS", 0, 30)
$(IFIOC_GALIL_01) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:MON3:,AXIS0=$(MYPVPREFIX)MOT:MON3,TOL=1,LOOKUP=LOOKUPFILE4","NUMPOS", 0, 30)
