   $(IFIOC_LINMOT_01=#) epicsEnvSet "LOOKUP_JM_FILE" "$(ICPCONFIGROOT)/motionSetPoints/jawmirror.txt"
 
   $(IFIOC_LINMOT_01=#) motionSetPointsConfigure("LOOKUP_JM","LOOKUP_JM_FILE", 1)
 
   $(IFIOC_LINMOT_01=#) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)JAWMIRROR:,NAME0=Position,AXIS0=$(MYPVPREFIX)MOT:JAWMIRROR,TOL=1,LOOKUP=LOOKUP_JM")
   $(IFIOC_LINMOT_01=#) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)JAWMIRROR:,NAME0=Position,AXIS0=$(MYPVPREFIX)MOT:JAWMIRROR,TOL=1,LOOKUP=LOOKUP_JM","NUMPOS", 0, 2)
