 # Setting up the Alignment Mirror
$(IFIOC_LINMOT_01) epicsEnvSet("LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/mirror.txt")

$(IFIOC_LINMOT_01) motionSetPointsConfigure("LOOKUPFILE1","LOOKUPFILE1", 1)

$(IFIOC_LINMOT_01) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:MIRROR:,NAME0=linear,AXIS0=$(MYPVPREFIX)MOT:MIRROR,TOL=0.1,LOOKUP=LOOKUPFILE1")

$(IFIOC_LINMOT_01) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPREFIX)LKUP:MIRROR:,AXIS0=$((MYPREFIX)MOT:MIRROR,TOL=1,LOOKUP=LOOKUPFILE1)
